## PhotoPrism: Computer Vision Models
## https://github.com/photoprism/photoprism-vision

services:
  ## Vision Describe Service, accessible through the following default endpoint URL:
  ## http://localhost:5000/api/v1/vision/describe
  vision-describe:
    ## Use photoprism/vision-describe:preview for testing preview builds:
    image: photoprism/vision-describe:latest
    stop_grace_period: 5s
    working_dir: "/app"
    ## Make the service accessible on port 5000 (only change the left-hand side if necessary, e.g. “80:5000”):
    ports:
      - "5000:5000"
    ## Set environment variables to configure the service (optional):
    environment:
      TF_CPP_MIN_LOG_LEVEL: 2                        # show all TensorFlow logs except INFO and WARNING
      ## Setting the following variables will run the service as a non-root user:
      # PHOTOPRISM_UID: 1000
      # PHOTOPRISM_GID: 1000
      # PHOTOPRISM_UMASK: 0000
    ## Share host devices to enable CPU/GPU hardware acceleration (optional):
    # devices:
    #  - "/dev/dri:/dev/dri"
    #  - "/dev/nvidia0:/dev/nvidia0"
    #  - "/dev/nvidiactl:/dev/nvidiactl"
    #  - "/dev/nvidia-modeset:/dev/nvidia-modeset"
    #  - "/dev/nvidia-nvswitchctl:/dev/nvidia-nvswitchctl"
    #  - "/dev/nvidia-uvm:/dev/nvidia-uvm"
    #  - "/dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools"
