## PhotoPrism® Computer Vision API
## https://github.com/photoprism/photoprism-vision
services:
  photoprism-vision:
    ## Use photoprism/vision:preview for testing preview builds:
    image: photoprism/vision:latest
    stop_grace_period: 5s
    working_dir: "/app"
    ## Make the service accessible on port 5000 (only change the left-hand side if necessary, e.g. “80:5000”):
    ports:
      - "5000:5000"
    ## Set environment variables to configure the service (optional):
    environment:
      TF_CPP_MIN_LOG_LEVEL: 2                        # show all TensorFlow logs except INFO and WARNING
      ## Setting the following variables will run the service as a non-root user:
      # PHOTOPRISM_UID: 1000
      # PHOTOPRISM_GID: 1000
      # PHOTOPRISM_UMASK: 0000
      ## Ollama configuration
      # OLLAMA_ENABLED: "true"
      # OLLAMA_HOST: "http://ollama:11434"
      # OLLAMA_NSFW_PROMPT: "detect NSFW"
      # OLLAMA_LABELS_PROMPT: "give me labels"
      # OLLAMA_CAPTION_PROMPT: "what is on the image?"
    ## Share host devices to enable CPU/GPU hardware acceleration (optional):
    # devices:
    #  - "/dev/dri:/dev/dri"
    #  - "/dev/nvidia0:/dev/nvidia0"
    #  - "/dev/nvidiactl:/dev/nvidiactl"
    #  - "/dev/nvidia-modeset:/dev/nvidia-modeset"
    #  - "/dev/nvidia-nvswitchctl:/dev/nvidia-nvswitchctl"
    #  - "/dev/nvidia-uvm:/dev/nvidia-uvm"
    #  - "/dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools"
