services:
  ## PhotoPrism® Computer Vision API,
  ## https://github.com/photoprism/photoprism-vision
  photoprism-vision:
    ## Use photoprism/vision:preview for testing preview builds:
    image: photoprism/vision:latest
    restart: unless-stopped
    stop_grace_period: 15s
    working_dir: "/app"
    ## Insecurely exposes the Vision service on port 5000
    ## without authentication (for private networks only):
    ports:
      - "5000:5000"
    user: 1000:1000
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    ## Set environment variables to configure the service (optional):
    environment:
      ## Service user configuration:
      PHOTOPRISM_UID: 1000
      PHOTOPRISM_GID: 1000
      ## Ollama client configuration
      OLLAMA_ENABLED: "true"
      OLLAMA_HOST: "http://ollama:11434"
      ## TensorFlow configuration:
      TF_CPP_MIN_LOG_LEVEL: 2                        # show all TensorFlow logs except INFO and WARNING
      # OLLAMA_NSFW_PROMPT: |
      #   Analyze this image and provide probability estimates in the following categories, ranging from 0 to 1 (higher values indicate a higher probability):
      #   Neutral: Likelihood that the content is neutral and not sexual in any way
      #   Drawing: Likelihood that the image is a sexual illustration or drawing
      #   Hentai: Likelihood that the image contains adult anime or manga content
      #   Porn: Likelihood that the image contains explicit adult content
      #   Sexy: Likelihood that the image contains suggestive adult content
      # OLLAMA_LABELS_PROMPT: |
      #   Generate one- or two-word labels that best describe the image.
      # OLLAMA_CAPTION_PROMPT: Create an interesting caption that sounds natural and briefly describes
      #   the visual content in up to 3 sentences. Avoid text formatting, meta-language,
      #   and filler words. Do not start captions with phrases such as "This image", "The
      #   image", "This picture", "The picture", "A picture of", "Here are", or "There is".
      #   Instead, start describing the content by identifying the subjects, location, and
      #   any actions that might be performed. Use explicit language to describe the scene
      #   if necessary for a proper understanding.
      ## NVIDIA Container Toolkit
      NVIDIA_VISIBLE_DEVICES: "all"
      NVIDIA_DRIVER_CAPABILITIES: "compute,utility"
    ## Share host devices to enable CPU/GPU hardware acceleration (optional):
    # devices:
    #  - "/dev/dri:/dev/dri"
    #  - "/dev/nvidia0:/dev/nvidia0"
    #  - "/dev/nvidiactl:/dev/nvidiactl"
    #  - "/dev/nvidia-modeset:/dev/nvidia-modeset"
    #  - "/dev/nvidia-nvswitchctl:/dev/nvidia-nvswitchctl"
    #  - "/dev/nvidia-uvm:/dev/nvidia-uvm"
    #  - "/dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools"
    deploy:
      resources:
        reservations:
          devices:
            - driver: "nvidia"
              capabilities: [ gpu ]
              count: "all"
    volumes:
      - models:/app/models
      - venv:/app/venv

  ## Ollama Large Language Models
  ## see https://ollama.com/search?c=vision
  ## Before use, you must run the "ollama pull [name:version]"
  ## command to download and install a model, for example:
  ## docker compose exec ollama ollama pull qwen2.5vl:3b
  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    stop_grace_period: 15s
    ## Insecurely exposes the Ollama service on port 11434
    ## without authentication (for private networks only):
    ports:
      - "11434:11434"
    environment:
      ## Ollama server configuration
      OLLAMA_HOST: "0.0.0.0:11434"
      OLLAMA_MODELS: "/root/.ollama" # model storage path (see volumes section below)
      OLLAMA_MAX_QUEUE: "100"        # maximum number of queued requests
      OLLAMA_NUM_PARALLEL: "1"       # maximum number of parallel requests
      OLLAMA_MAX_LOADED_MODELS: "1"  # maximum number of loaded models per GPU
      OLLAMA_LOAD_TIMEOUT: "5m"      # maximum time for loading models (default "5m")
      OLLAMA_KEEP_ALIVE: "10m"       # duration that models stay loaded in memory (default "5m")
      OLLAMA_CONTEXT_LENGTH: "4096"  # maximum input context length
      OLLAMA_MULTIUSER_CACHE: "1"    # optimize prompt caching for multi-user scenarios
      # OLLAMA_DEBUG: "1"              # shows additional debug information
      # OLLAMA_NOPRUNE: "1"            # disables pruning of model blobs at startup
      # OLLAMA_NOHISTORY: "1"          # disables readline history
      # OLLAMA_FLASH_ATTENTION: "1"    # enables the experimental flash attention feature
      # OLLAMA_SCHED_SPREAD: "1"       # allows scheduling models across all GPUs.
      # OLLAMA_GPU_OVERHEAD: "0"       # reserves a portion of VRAM per GPU (bytes)
      # OLLAMA_INTEL_GPU: "1"          # enables experimental Intel GPU detection
      ## NVIDIA GPU Hardware Acceleration (see https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html):
      NVIDIA_VISIBLE_DEVICES: "all"
      NVIDIA_DRIVER_CAPABILITIES: "compute,utility"
    volumes:
      - "ollama:/root/.ollama"
    ## NVIDIA GPU Hardware Acceleration (see https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html):
    deploy:
      resources:
        reservations:
          devices:
            - driver: "nvidia"
              capabilities: [ gpu ]
              count: "all"

## Create named volume for ollama models
volumes:
  models:
  venv:
  ollama:
    driver: local