services:
  ## PhotoPrism® Computer Vision API,
  ## https://github.com/photoprism/photoprism-vision
  photoprism-vision:
    ## Use photoprism/vision:preview for testing preview builds:
    image: photoprism/vision:latest
    stop_grace_period: 5s
    working_dir: "/app"
    ## Make the service accessible on port 5000 (only change the left-hand side if necessary, e.g. “80:5000”):
    ports:
      - "5000:5000"
    user: 1000:1000
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    ## Set environment variables to configure the service (optional):
    environment:
      ## Service user configuration:
      PHOTOPRISM_UID: 1000
      PHOTOPRISM_GID: 1000
      ## Ollama client configuration
      OLLAMA_ENABLED: "true"
      OLLAMA_HOST: "http://ollama:11434"
      ## TensorFlow configuration:
      TF_CPP_MIN_LOG_LEVEL: 2                        # show all TensorFlow logs except INFO and WARNING
      # OLLAMA_NSFW_PROMPT: "detect NSFW"
      # OLLAMA_LABELS_PROMPT: "give me labels"
      # OLLAMA_CAPTION_PROMPT: "what is on the image?"
      ## NVIDIA Container Toolkit
      NVIDIA_VISIBLE_DEVICES: "all"
      NVIDIA_DRIVER_CAPABILITIES: "compute,utility"
    ## Share host devices to enable CPU/GPU hardware acceleration (optional):
    # devices:
    #  - "/dev/dri:/dev/dri"
    #  - "/dev/nvidia0:/dev/nvidia0"
    #  - "/dev/nvidiactl:/dev/nvidiactl"
    #  - "/dev/nvidia-modeset:/dev/nvidia-modeset"
    #  - "/dev/nvidia-nvswitchctl:/dev/nvidia-nvswitchctl"
    #  - "/dev/nvidia-uvm:/dev/nvidia-uvm"
    #  - "/dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools"
    deploy:
      resources:
        reservations:
          devices:
            - driver: "nvidia"
              capabilities: [ gpu ]
              count: "all"
    volumes:
      - models:/app/models
      - venv:/app/venv

  ## Ollama Large Language Models
  ## https://github.com/ollama/ollama
  ## To install models listed at https://github.com/ollama/ollama?tab=readme-ov-file#model-library:
  ## docker exec -it ollama ollama run llama3
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    environment:
      ## Ollama server configuration
      OLLAMA_HOST: "0.0.0.0:11434"
      OLLAMA_MAX_LOADED_MODELS: "2"
      OLLAMA_NUM_PARALLEL: "2"
      OLLAMA_MAX_QUEUE: "100"
      OLLAMA_KEEP_ALIVE: "-1"
      OLLAMA_MODELS: "/root/.ollama"
      ## NVIDIA Container Toolkit
      NVIDIA_VISIBLE_DEVICES: "all"
      NVIDIA_DRIVER_CAPABILITIES: "compute,utility"
    volumes:
      - "ollama:/root/.ollama"
    deploy:
      resources:
        reservations:
          devices:
            - driver: "nvidia"
              capabilities: [ gpu ]
              count: "all"

## Create named volume for ollama models
volumes:
  models:
  venv:
  ollama:
    driver: local