## FOR TEST AND DEVELOPMENT ONLY, DO NOT USE IN PRODUCTION
## see https://github.com/photoprism/photoprism-vision

services:
  ## PhotoPrism® Computer Vision API
  ## Endpoint: http://localhost:5000/api/v1/vision/caption
  photoprism-vision:
    ## Build image from source code:
    build: .
    image: photoprism/vision:develop
    stop_grace_period: 5s
    entrypoint: ["/app/venv/bin/flask"]
    command: ["--app", "app", "run", "--debug", "--host", "0.0.0.0"]
    working_dir: "/app"
    ## Make the service accessible on port 5000 (only change the left-hand side if necessary, e.g. “80:5000”):
    ports:
      - "5000:5000"
    user: 1000:1000
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    ## Set environment variables to configure the service (optional):
    environment:
      TF_CPP_MIN_LOG_LEVEL: 1                        # show TensorFlow debug logs
      ## Service user configuration:
      PHOTOPRISM_UID: 1000
      PHOTOPRISM_GID: 1000
      # PHOTOPRISM_UMASK: 0000
      ## Ollama client configuration
      OLLAMA_ENABLED: "true"
      OLLAMA_HOST: "http://ollama:11434"
      # OLLAMA_NSFW_PROMPT: |
      #   Analyze this image and provide probability estimates in the following categories, ranging from 0 to 1 (higher values indicate a higher probability):
      #   Neutral: Likelihood that the content is neutral and not sexual in any way
      #   Drawing: Likelihood that the image is a sexual illustration or drawing
      #   Hentai: Likelihood that the image contains adult anime or manga content
      #   Porn: Likelihood that the image contains explicit adult content
      #   Sexy: Likelihood that the image contains suggestive adult content
      # OLLAMA_LABELS_PROMPT: |
      #   Generate one- or two-word labels that best describe the image.
      # OLLAMA_CAPTION_PROMPT: Create an interesting caption that sounds natural and briefly describes
      #   the visual content in up to 3 sentences. Avoid text formatting, meta-language,
      #   and filler words. Do not start captions with phrases such as "This image", "The
      #   image", "This picture", "The picture", "A picture of", "Here are", or "There is".
      #   Instead, start describing the content by identifying the subjects, location, and
      #   any actions that might be performed. Use explicit language to describe the scene
      #   if necessary for a proper understanding.
      ## NVIDIA Container Toolkit
      NVIDIA_VISIBLE_DEVICES: "all"
      NVIDIA_DRIVER_CAPABILITIES: "compute,utility"
    ## Share host devices to enable CPU/GPU hardware acceleration (optional):
    # devices:
    #  - "/dev/dri:/dev/dri"
    #  - "/dev/nvidia0:/dev/nvidia0"
    #  - "/dev/nvidiactl:/dev/nvidiactl"
    #  - "/dev/nvidia-modeset:/dev/nvidia-modeset"
    #  - "/dev/nvidia-nvswitchctl:/dev/nvidia-nvswitchctl"
    #  - "/dev/nvidia-uvm:/dev/nvidia-uvm"
    #  - "/dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools"
    ## Mount current service directory for local development:
    volumes:
       - ".:/app"
       - "python-venv:/app/venv"
    deploy:
      resources:
        reservations:
          devices:
            - driver: "nvidia"
              count: 1
              capabilities: [ gpu ]

volumes:
  python-venv:
    driver: local

networks:
  default:
    name: photoprism
    external: true
